### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by yaaaaashiki** [yaaaaashiki/Escapism#215]
## TODO for release 
- [x] Remove chat feature (table, model, controller, etc...)
- [x] Implement contact page (related #210) 
- [x]  Fix carousel's text color
- [x] Fix senior member comment's link in top page
- [x] Add unicorn env
- [x] Add nginx env
- [x] Add production's seed data
- [x] Add shell script for production's database.yml 
- [x] Precomplie assets files
- [x] Fix mail's description for request URI
- [x] Add register year's description
- [ ] Change from HTTP to HTTPS
- [x] Fix professor name to uppercase
- [x] Add Google analytics
- [x] Clean up server and failed mail logs
- [x] Add user's labo id information when registering user 
- [x] Check all operations
- [x] Remove parenthesis in Martin lab's description (related #230) 
- [x] Update lab's assistant professor name (related #231)
- [ ] How to take over this app
- [ ] Should we remove bad theses??
- [x] Add Yamaguchi lab's abstract (related #264)

**Comment by yaaaaashiki** [comment]
Merged!
