### ISSUE TITLE
新しい論文データの挿入方法

### ISSUE THREAD

**Issue by yaaaaashiki** [yaaaaashiki/Escapism#220]
# TODO
- [x] index.html のテンプレートを提案・発行
- [x] 佐久田先生から OK をもらう
- [x] 教授会で OK をもらう

# やりたいこと
当初はindex.htmlから読み込む予定だったけど、aタグのhref属性の書き間違いとかを考えると直接入力してもらったほうがみんなHappyになるから以下2つをやりたい

- 研究室ごとに任意のディレクトリ構造でpdfをアップロードして保存する（一時ディレクトリに保存）  
    ↑任意の構造じゃなくてもいいけど、作る手間を考えたら(ry

- index.htmlを作成する

# 実装すること
### 1.1 入力項目
- 研究室名  
    文字列（プルダウンメニューで選択）

- 年度  
    文字列(プルダウンメニューで選択)

- 複数のpdfファイル(ディレクトリ構造ごと)  
    ファイル
    (```<input type="file" webkitdirectory>```で取得可能だけどIEは使えない)

- タイトル  
    文字列

- 著者名  
    文字列

- 論文の分類  
    文字列（卒業論文、修士論文、博士論文？？）

- 抄録、要旨、英文、著者紹介などのオプション

### 1.2 こんな感じがいいなwww
0. 研究室名と年度を選択  
    研究室名がなかったら、別途登録(このissueではやらない)

1. pdfファイルを含むディレクトリを「```<input type="file" webkitdirectory>```」で選択

2. 1.で選択したときの"change"イベントでディレクトリ以下に含まれるpdfの相対PATHを取得して画面に表示  
    相対PATHはchangeイベントに渡される```event.target.files[i].webkitRelativePath```で取得可能

3. 表示されたPATHに対応するタイトルと著者名などの情報を入力する  
    抄録、要旨、英文、著者紹介などのオプションはEscpism自体には必要ないのでいい感じにwww
    (index.htmlを作成するときにPATHだけわかれば良い)

4. 送信ボタンでアップロード  
    上記2で書いたwebkitRelativePathも送信しないとディレクトリ構造がrailsに伝わらないらしい  
    (webの情報だからやってみないと分からない)

### 2.1 仕様
- アップロードされたpdfファイルを保存  
    以下のディレクトリに、アップロードされたディレクトリ構造のまま保存

    以下のディレクトリが既に存在するときはいい感じにマージする。  
    ↑考えるのが面倒くさいから後勝ちでいいかも

    ProjectRoot/thesis_data/ignore/年度/研究室名(英字)/  

- コントローラで受け取った情報を元にデータベースに保存  
    Thesisテーブルのスキーマを変更する必要があれば変更する

    (ActiveRecordを用いて保存すればElasticSearchにも自動で保存される)

### 3.1 仕様
- 送信ボタンのレスポンスとしてindex.htmlを作成してダウンロードさせる  
    zipでpdfごと返してもいいけど手元で解凍するのとか実装とかファイルの容量がでかくでダウンロードに時間がかかるのとかを考えるのが面倒くさい

# 注意事項
railsまたはnginxでアップロードするファイル容量の最大値を指定しないとDOS攻撃ができる()

**Comment by yaaaaashiki** [comment]
merged
